"""initial schema

Revision ID: 05167ff0ec5d
Revises: 
Create Date: 2026-04-22 15:30:48.583881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05167ff0ec5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('daily_budget_limit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('daily_spend_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('daily_spend_date', sa.Date(), nullable=True),
    sa.Column('qps_limit', sa.Integer(), nullable=False),
    sa.Column('allowed_logical_models_json', sa.JSON(), nullable=False),
    sa.Column('request_content_logging_enabled', sa.Boolean(), nullable=False),
    sa.Column('response_content_logging_enabled', sa.Boolean(), nullable=False),
    sa.Column('end_user', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_status'), ['status'], unique=False)

    op.create_table('logical_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('routing_strategy', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logical_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logical_models_name'), ['name'], unique=True)

    op.create_table('provider_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('openai_endpoint', sa.String(length=255), nullable=True),
    sa.Column('anthropic_endpoint', sa.String(length=255), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('upstream_model_name', sa.String(length=120), nullable=False),
    sa.Column('input_token_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('output_token_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('supports_prompt_cache', sa.Boolean(), nullable=False),
    sa.Column('cache_read_token_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cache_write_token_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_models_name'), ['name'], unique=True)

    op.create_table('balance_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_usage_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'summary_date', name='uq_api_key_summary_date')
    )
    op.create_table('logical_model_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logical_model_id', sa.Integer(), nullable=False),
    sa.Column('provider_model_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['logical_model_id'], ['logical_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_model_id', 'provider_model_id', name='uq_logical_provider_route')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('logical_model_id', sa.Integer(), nullable=True),
    sa.Column('provider_model_id', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('call_type', sa.String(length=32), nullable=True),
    sa.Column('upstream_request_id', sa.String(length=128), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_user', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['logical_model_id'], ['logical_models.id'], ),
    sa.ForeignKeyConstraint(['provider_model_id'], ['provider_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_logs_end_user'), ['end_user'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_request_logs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_upstream_request_id'), ['upstream_request_id'], unique=False)

    op.create_table('request_log_bodies',
    sa.Column('request_log_id', sa.Integer(), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_log_id'], ['request_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_log_id')
    )
    op.create_table('usage_records',
    sa.Column('request_log_id', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('input_token_price_snapshot', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('output_token_price_snapshot', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cache_read_price_snapshot', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cache_write_price_snapshot', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_input', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_output', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_cache_read', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_cache_write', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['request_log_id'], ['request_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_records')
    op.drop_table('request_log_bodies')
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_upstream_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_started_at'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_end_user'))

    op.drop_table('request_logs')
    op.drop_table('logical_model_routes')
    op.drop_table('daily_usage_summaries')
    op.drop_table('balance_ledgers')
    with op.batch_alter_table('provider_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_models_name'))

    op.drop_table('provider_models')
    with op.batch_alter_table('logical_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logical_models_name'))

    op.drop_table('logical_models')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_status'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
