-- Migration: 1.0.1
-- Description: <one-line summary of what this migration does>
--
-- !! IMPORTANT: If you configured a custom TABLE_PREFIX (default: "lr_"),
-- !! replace every occurrence of "lr_" in this file with your prefix
-- !! before running. Example: s/lr_/myprefix_/g
--
-- Apply (MySQL):
--   mysql -u llm_router -p llm_router < migrations/1.0.1/migration_mysql_1.0.1.sql
